### ISSUE TITLE
Non content

### ISSUE THREAD

**Issue by Jnowox** [PyPiSan/KinAni#23]
![Screenshot_20240811_232526_KinAni](https://github.com/user-attachments/assets/ef52c5bb-bf12-4df8-bab6-f8954b8551bd)

**Comment by PyPiSan** [comment]
What is the name of drama/anime?

**Comment by Jnowox** [comment]
Is doing the same thing with all animes and movies, dramas are working fine

**Comment by PyPiSan** [comment]
Ok, I got the issue will, resolve it.

**Comment by PyPiSan** [comment]
This is resolved.

**Comment by PyPiSan** [comment]
@Jnowox the reply through app (when raising an issue) is not yet implemented. I will implement that later.
